### ISSUE TITLE
cut new version on the puppet forge

### ISSUE THREAD

**Issue by edestecd** [luizvasconceloss/hiera-ssm-paramstore#17]
Bump version in metadata.json and deploy to the forge.

You can get travis to do this for you automatically when you make a git tag like this: `v1.0.0`
Just add this section to your .sync.yml: https://github.com/edestecd/puppet-clamav/blob/master/.sync.yml#L7

You can get the encrypted secure password by installing the travis gem:
```shell
gem install travis
travis encrypt <your forge password>
```

Use pdk to update `.travis.yml` from your `.sync.yml`:
```shell
pdk update
```

**Comment by luizvasconceloss** [comment]
Thank you for this suggestion and for the contributions! The latest changes are now published as version 1.0.0
