### ISSUE TITLE
AWS credentials not found

### ISSUE THREAD

**Issue by duffrecords** [luizvasconceloss/hiera-ssm-paramstore#2]
I'm trying to test this module out in a virtual machine on my workstation but I get the error:
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, unable to sign request without credentials set`
If I comment out the SSM Parameter Store section of `hiera.yaml` the agent runs without any problems.  I've tried adding my AWS credentials to `~/.aws/` and also exporting `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as environment variables but the agent can't find them.  Did you have to do anything different to make it work?

**Comment by luizvasconceloss** [comment]
Hello there,

I'm trying to replicate it, I've tested using ~/.aws/credentials file and environment variable and it seems to be working fine. However, it might happen when using sudo, to successfully run using sudo it would be necessary to use 'sudo -E' to preserve the environment variables or configure the credentials in /root/.aws/credentials instead of ~/.aws/credentials.

**Comment by duffrecords** [comment]
Hmm, that brings up a good point.  I should clarify my comment--I'm running `puppet agent -t` as root, with the credentials stored in `/root/.aws/credentials` so that should rule out any side effects from switching users.  Are you running it as a service?  I wonder if these variables are not available by default in the systemd environment.

**Comment by luizvasconceloss** [comment]
I've been using it masterless and with agent/master (agent running as service), the difference is that when using masterless the node requires the credentials as the catalog will be compiled on it, but moving to an agent/master infrastructure the master needs credentials as the catalog is compiled in the master.
As you are running 'puppet agent -t' I presume that is an agent/master model, so should be only necessary to configure the credentials in the master.
I'll try to reproduce it, could you provide this information:
- which OS is been used on the master and node
- is it puppet opensource or enterprise
- puppet version
- are you able to get the key value using puppet lookup?

**Comment by duffrecords** [comment]
It's Puppet 5.4.0 community version, running on CentOS 7.5.  I set up my `hiera.yaml` similarly to the example in the documentation:
```yaml
---
version: 5

hierarchy:
  - name: "AWS Parameter Store"
    lookup_key: hiera_ssm_paramstore
    uris:
      - /
      - /hiera/%{facts.os.family}/
    options:
      region: us-east-2
      get_all: false
```

I created a key `/foo` and `/hiera/RedHat/foo` to test both URIs.  The AWS CLI returns the key successfully:
```
[root@puppet ~]# aws ssm get-parameters --names /hiera/RedHat/foo
{
    "InvalidParameters": [],
    "Parameters": [
        {
            "Version": 1,
            "Type": "String",
            "Name": "/hiera/RedHat/foo",
            "Value": "bar"
        }
    ]
}
```

But I don't get any results using puppet lookup:
```
  Searching for "foo"
    Global Data Provider (hiera configuration version 5)
      Using configuration "/etc/puppetlabs/puppet/hiera.yaml"
      Hierarchy entry "AWS Parameter Store"
        URI "/"
          Original uri: "/"
          No such key: "foo"
          Looking for /foo
          Key /foo not found
        URI "/hiera/RedHat/"
          Original uri: "/hiera/%{facts.os.family}/"
          No such key: "foo"
          Looking for /hiera/RedHat/foo
          Key /hiera/RedHat/foo not found
```

**Comment by duffrecords** [comment]
The problem ended up being a case of user error, but your suggestion to try `puppet lookup` led me in the right direction, so thanks for taking the time to help me.  Sometimes the most innocuous mistake can cause everything to fail silently--I had configured `hiera.yaml` to use `us-east-2` instead of `us-west-2`.  Thanks again, I'm excited to start using your module to move secrets out of Hiera!
